format = """$username\
$hostname\
$status\
([${env_var.SECOND}${custom.PARENT}](blue))\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$nix_shell\
$python\
$line_break\
$character"""

[nix_shell]
format="[â„ï¸ $name](fg:75)"

[custom.PARENT]
when='''test $PARENT'''
command='basename $PARENT'
format='[$output ](blue)'
disabled=false

[env_var.SECOND]
variable='SECOND'
format='[ğŸ‘¼ $env_value ](blue)'
disabled=false

[custom.mako_node]
when='''git rev-parse --git-dir'''
command='''git tag | rg "^mko[0-9]+$" | tail -n 1 '''
format='[$output ](fg:230)'


[directory]
style = "fg:182"

[character]
success_symbol = "[â¯](fg:225)"
error_symbol = "[â¯](fg:124)"

[git_branch]
symbol = "ğŸŒ±"
format = "[$branch]($style)"
style = "fg: 217"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "â€‹"
untracked = "â€‹"
modified = "â€‹"
staged = "â€‹"
renamed = "â€‹"
deleted = "â€‹"
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "fg:217"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
